version: '3.4'
services:
  postgresql:
    image: postgres:14.7-alpine3.17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
